# Generated by Django 4.2.6 on 2023-10-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0004_category_image_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category name'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
