# Generated by Django 4.2.6 on 2023-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0008_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(to='shopping_cart_app.subcategory'),
        ),
    ]
