# Generated by Django 4.2.6 on 2023-10-26 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0015_remove_customuser_address_addressmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
