# Generated by Django 4.2.6 on 2023-10-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0016_alter_addressmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.product')),
            ],
        ),
    ]
