# Generated by Django 4.2.6 on 2023-11-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0029_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.orderitem'),
        ),
    ]
