# Generated by Django 4.2.6 on 2023-11-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0032_remove_cart_cartitems_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.cartitem'),
        ),
    ]
