# Generated by Django 4.2.6 on 2023-11-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0033_alter_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.cart'),
        ),
    ]
