# Generated by Django 4.2.6 on 2023-11-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0036_alter_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.orderitem'),
        ),
    ]
