export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILURE = "CATEGORY_LIST_FAILURE";
export const CATEGORY_LIST_RESET = "CATEGORY_LIST_RESET";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";
export const ADD_CATEGORY_RESET = "ADD_CATEGORY_RESET";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";
export const GET_CATEGORY_RESET = "GET_CATEGORY_RESET";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";

export const ADD_SUB_CATEGORY_REQUEST = "ADD_SUB_CATEGORY_REQUEST";
export const ADD_SUB_CATEGORY_SUCCESS = "ADD_SUB_CATEGORY_SUCCESS";
export const ADD_SUB_CATEGORY_FAILURE = "ADD_SUB_CATEGORY_FAILURE";
export const ADD_SUB_CATEGORY_RESET = "ADD_SUB_CATEGORY_RESET";

export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAILURE = "GET_SUB_CATEGORY_FAILURE";
export const GET_SUB_CATEGORY_RESET = "GET_SUB_CATEGORY_RESET";

export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAILURE = "DELETE_SUB_CATEGORY_FAILURE";
export const DELETE_SUB_CATEGORY_RESET = "DELETE_SUB_CATEGORY_RESET";
