export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";
export const GET_PRODUCT_LIST_RESET = "GET_PRODUCT_LIST_RESET";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const GET_FILTERED_PRODUCTS_LIST_REQUEST =
  "GET_FILTERED_PRODUCTS_LIST_REQUEST";
export const GET_FILTERED_PRODUCTS_LIST_SUCCESS =
  "GET_FILTERED_PRODUCTS_LIST_SUCCESS";
export const GET_FILTERED_PRODUCTS_LIST_FAILURE =
  "GET_FILTERED_PRODUCTS_LIST_FAILURE";
export const GET_FILTERED_PRODUCTS_LIST_RESET =
  "GET_FILTERED_PRODUCTS_LIST_RESET";

export const GET_BRAND_LIST_REQUEST = "GET_BRAND_LIST_REQUEST";
export const GET_BRAND_LIST_SUCCESS = "GET_BRAND_LIST_SUCCESS";
export const GET_BRAND_LIST_FAILURE = "GET_BRAND_LIST_FAILURE";
export const GET_BRAND_LIST_RESET = "GET_BRAND_LIST_RESET";
